name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:

jobs:
  test:

    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install

    - name: Run tests
      run: scripts/test.sh
